 [[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200

[[redirects]]
from = "/proxy/*"
  to = "https://calm-shortbread-d2aa50.netlify.app:splat"  
  status = 200
  force = true
